### ISSUE TITLE
Textarea rendering

### ISSUE THREAD

**Issue by NduatiK** [edisonywh/backoffice#43]
Hi, 
I've been using backoffice to edit text in a blog-like application. In most cases, we expect multiple sentences and perhaps multiple paragraphs.

To make editing easy, I have been using the `:textarea` type on my form field. This however produces json encoded strings.

![image](https://user-images.githubusercontent.com/28830783/115838202-18fcdc00-a422-11eb-8330-bdd7916fda65.png)

Not pretty or easy to use.

This seems to be caused by the `Phoenix.json_library().encode` applied to the text [here](https://github.com/edisonywh/backoffice/blob/3bf35789f40df5c8914d155815ce85cd6c43da80/lib/backoffice/field.ex#L45)

Removing the json encoding seems to resolve the issue

![image](https://user-images.githubusercontent.com/28830783/115838087-fa96e080-a421-11eb-8301-229369e7cfcd.png)

**Comment by NduatiK** [comment]
Could the encoding be removed? Does it serve a specific purpose?

**Comment by edisonywh** [comment]
Ah great catch, I was testing out the `:textarea` form input with editing `:map`, you can see here [the implementation](https://github.com/edisonywh/backoffice/blob/3bf35789f40df5c8914d155815ce85cd6c43da80/lib/backoffice/field.ex#L81) just delegates to `:textarea`.

I think we should separate them so encoding is only called for `:map` type and not `:textarea`

**Comment by NduatiK** [comment]
Makes sense
