### ISSUE TITLE
Filter UI appearance

### ISSUE THREAD

**Issue by NduatiK** [edisonywh/backoffice#46]
Looking at pull request #41, I expect the UI below.

![image](https://user-images.githubusercontent.com/28830783/115995815-6a08fd80-a5e5-11eb-8670-ddb75dcc2b00.png)

However, I am instead getting:

![image](https://user-images.githubusercontent.com/28830783/115995891-bfdda580-a5e5-11eb-9251-989136fb77f8.png)

The padding and alignments are off. @edisonywh, are you providing some styling locally that are not in the library?

**Comment by edisonywh** [comment]
Ah great catch. We purge unused Tailwind CSS and we need to do that manually, and I forgot to do that in this case.

This also has to do with how I develop, I develop Backoffice directly against my app (Slick Inbox), but I should probably come up with a better way, like a separate demo app or something (I plan to have a proper demo app when Backoffice is more stable).

Anyway, I've fixed this in #47. Thanks for reporting!

**Comment by NduatiK** [comment]
This fixes the layout issue but introduces a small issue with the input fields.
The border color and padding are lost.

![image](https://user-images.githubusercontent.com/28830783/115998283-36cb6c00-a5ef-11eb-870b-6ed6d7882e4a.png)

**Comment by edisonywh** [comment]
Mhm that's really strange.. what css classes are supposed to be on there?

**Comment by NduatiK** [comment]
I think the question should actually be something along the lines of "why is tailwind (or purgecss) purging more classes than we expect?".

I am not very familiar with html and css (long live Elm), so the following is based on a couple of minutes of research.

---

1. Tailwind purges unused selectors
2. We don't have selectors for inputs because we are using Phoenix.Html.Form methods and not html. For example purging removed the following css (among others):
    ```
    [type='text'],
    [type='date'],
    [type='search'],
    [type='time'],
    textarea,
    select
    {
        -webkit-appearance: none;
        -moz-appearance: none;
            appearance: none;
        ...
    }
    ```
4. We therefore need to tell tailwind to not purge "normalization"  css (This was discussed in [Tailwinds Github issues](https://github.com/tailwindlabs/tailwindcss-forms/issues/43#issuecomment-782256190))
5. The solution is given [here](https://github.com/tailwindlabs/tailwindcss-forms/issues/43#issuecomment-791465128). We simply whitelist the base layer of tailwind. Here is the snippet for suggested solutiion:
```
// tailwind.config.js
module.exports = {
  purge: {
    layers: ['components', 'utilities'],
    content: ['./src/**/*.html'],
  },
  // ...
}
```
